# Generated by Django 5.1.2 on 2024-11-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="books/", verbose_name="Загрузите обложку"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Введите название книги"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Введите цену")),
                ("release_date", models.DateField(verbose_name="Введите дату выхода")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Комедия", "Комедия"),
                            ("Драма", "Драма"),
                            ("Ужасы", "Ужасы"),
                            ("Романтика", "Романтика"),
                        ],
                        max_length=100,
                        verbose_name="Введите жанр",
                    ),
                ),
                (
                    "author_email",
                    models.CharField(
                        max_length=100, verbose_name="Введите email автора"
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=100, verbose_name="Введите имя автора"),
                ),
            ],
            options={
                "verbose_name": "книга",
                "verbose_name_plural": "книги",
            },
        ),
    ]
