# Generated by Django 5.1.2 on 2024-11-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hashtags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="age",
            name="age",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
