# Generated by Django 5.1.2 on 2024-11-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_devices", "0003_remove_category_devices_device_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mobile_devices.category",
            ),
        ),
    ]
