# Generated by Django 5.1.2 on 2024-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.IntegerField(
                null=True, verbose_name="Введите Ваш номер телефона"
            ),
        ),
    ]
